fix: update CFLAGS and CXXFLAGS to use -fPIC and pipe options in Dockerfile

diff --git a/python-versions/Dockerfile b/python-versions/Dockerfile
--- a/python-versions/Dockerfile
+++ b/python-versions/Dockerfile
@@ -19,8 +19,8 @@ ARG ACTIONS_PYTHON_VERSIONS
 ENV DEBIAN_FRONTEND=noninteractive \
     CC=gcc \
     CXX=g++ \
-    CFLAGS="-O3 -march=native" \
-    CXXFLAGS="-O3 -march=native"
+    CFLAGS="-O3 -fPIC -pipe" \
+    CXXFLAGS="-O3 -fPIC -pipe"
 
 # Set up the time zone
 RUN export DEBIAN_FRONTEND=noninteractive && \
@@ -36,12 +36,12 @@ RUN export DEBIAN_FRONTEND=noninteractive && \
     pkgs="g++ gcc git libz-dev make pkg-config python3 sudo build-essential libffi-dev libssl-dev zlib1g-dev libncurses-dev libbz2-dev libreadline-dev libsqlite3-dev uuid-dev libgdbm-dev liblzma-dev tk-dev libmpdec-dev libbluetooth-dev"; \
     apt-get -qq update -y && \
     for pkg in $pkgs; do \
-        echo "-----------------------------------------"; \
-        echo "Attempting to install: $pkg"; \
-        apt-get -qq -y install "$pkg" || { \
-            echo "WARNING: Could not install '$pkg'. It might not be available for your system or there was an error."; \
-            echo "Continuing with the next package..."; \
-        }; \
+    echo "-----------------------------------------"; \
+    echo "Attempting to install: $pkg"; \
+    apt-get -qq -y install "$pkg" || { \
+    echo "WARNING: Could not install '$pkg'. It might not be available for your system or there was an error."; \
+    echo "Continuing with the next package..."; \
+    }; \
     done; \
     apt-get clean && \
     rm -rf /var/lib/apt/lists/*
@@ -62,9 +62,9 @@ RUN pwsh \
     -NonInteractive \
     -ExecutionPolicy Bypass \
     -Command "& { \
-        \$ErrorActionPreference = 'Stop'; \
-        ./builders/build-python.ps1 '${PYTHON_VERSION}' linux '${TARGETARCH}'; \
-        exit \$LASTEXITCODE \
+    \$ErrorActionPreference = 'Stop'; \
+    ./builders/build-python.ps1 '${PYTHON_VERSION}' linux '${TARGETARCH}'; \
+    exit \$LASTEXITCODE \
     }"
 
 # ================= FINAL STAGE =====================
